M48
; DRILL file {KiCad 8.0.1} date 2024-04-08T22:07:58+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-08T22:07:58+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X8.1484Y-3.5266
X8.1484Y-3.7175
T2
X8.2677Y-3.5148
X8.2677Y-3.7293
M30
