M48
; DRILL file {KiCad (6.0.7-1)-1} date 2022 November 01, Tuesday 15:55:09
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-01T15:55:09+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X8.1484Y-3.5266
X8.1484Y-3.7175
T2
X8.2677Y-3.5148
X8.2677Y-3.7293
T0
M30
